### PR TITLE
Add Laravel 7 support

### PR DESCRIPTION
**Pull request by inxilpro**
- [x] Added or updated tests
- [x] Added or updated the [README.md](../README.md)
- [x] Detailed changes in the [CHANGELOG.md](../CHANGELOG.md) unreleased section

**Related Issue/Intent**

This just bumps up the dependency constraints to allow for Laravel 7 (which will be released tomorrow!)

### CODE REVIEW

**Comment by BenSampo** [comment]
Tests are failing

**Comment by inxilpro** [comment]
7.0 isn’t stable yet, to its failing on the `minimum-stability` flag. It should pass on Wed.

**Comment by Nevoss** [comment]
Can you try to run it again? I want to install it in my Laravel 7 project.

**Comment by BenSampo** [comment]
Blocked by https://github.com/hanneskod/classtools/pull/18

**Comment by NickJorens** [comment]
hanneskod/classtools#19 fixed this issue. Please merge. :)

**Comment by BenSampo** [comment]
Released as v1.33

**Pull request merged**
