### PR TITLE
Trait QueryEnums has been added.\n added features are query flaggedEn…

### PR DESCRIPTION
**Pull request by abilogos**
…um column

- [ ] Added or updated tests
- [* ] Added or updated the [README.md](../README.md)
- [ *] Detailed changes in the [CHANGELOG.md](../CHANGELOG.md) unreleased section

**Related Issue/Intent**

"Resolves Issue #155",

**Changes**

A new Trait has been introduced to be use for any query builder methods.

**Breaking changes**

### CODE REVIEW

**Comment by abilogos** [comment]
Hello @BenSampo , I have Made The Trait as You Suggested.

if its Ok, im considering to Add Methods to The Trait:

like **WhereIs** or **WhereIsNot** for non-Flagged Enums to use

**Comment by BenSampo** [comment]
Thanks @abilogos.

Can you add tests please?

**Comment by obennaci** [comment]
Is this feature still wanted? Could make a new PR since this seems abandoned.

**Comment by basepack** [comment]
@obennaci I was just looking for this kind of Eloquent functions. Would be nice if added.

**Comment by BenSampo** [comment]
Please go ahead @obennaci . There are some details here you might find useful: https://github.com/BenSampo/laravel-enum/issues/140.

I'm going to close this PR for now.

**Pull request closed without merging**
