### PR TITLE
Test multiple Laravel versions in Travis

### PR DESCRIPTION
**Pull request by spawnia**
Travis now runs tests on Laravel versions 5.6 through 6.0.

Change the PHP versions to include 7.4 instead of 7.1.

### CODE REVIEW

**Comment by BenSampo** [comment]
I'm watching this one with interest. I had a crack at the same thing a while back and ultimately gave up.

**Comment by spawnia** [comment]
Haha yeah, i have been through the gauntlet in https://github.com/nuwave/lighthouse

**Comment by spawnia** [comment]
`composer` seems to be running out of memory during the installation of certain Laravel versions https://travis-ci.org/BenSampo/laravel-enum/jobs/570704034. So far, i tried changing the memory limit, but to no success.

What else could we do to resolve this?

**Comment by spawnia** [comment]
@BenSampo gave this another shot and finally got something working.

Laravel 5.5 still hangs on install, which is why it is not included for now. This is still an improvement, as this tests Laravel 5.6 through 6.0

Also, in the meantime, support for PHP 7.1 has stopped. I removed it from the test matrix, as it requires some particular workarounds.

**Comment by BenSampo** [comment]
Nice one getting this to work @spawnia !

**Pull request merged**
