### PR TITLE
Support Laravel 11

### PR DESCRIPTION
**Pull request by spawnia**

### CODE REVIEW

**Comment by spawnia** [comment]
Requires https://github.com/symplify/rule-doc-generator to support Laravel 11.

**Comment by spawnia** [comment]
Thanks @eshimischi, awaiting a tag following 12.1.2, see https://github.com/symplify/rule-doc-generator/tags.

**Comment by websitevirtuoso** [comment]
merge it please

**Comment by miqayelsrapionyan** [comment]
@spawnia the tag 12.1.2 is already there, awaiting you PR.

**Comment by eshimischi** [comment]
> Thanks @eshimischi, awaiting a tag following 12.1.2, see https://github.com/symplify/rule-doc-generator/tags.

now it's ready https://github.com/symplify/rule-doc-generator/releases/tag/12.1.3

**Pull request merged**
