### PR TITLE
Fix regex error

### LINKED ISSUE #120: AbstractAnnotationCommand fails with PREG_JIT_STACKLIMIT_ERROR on large existing docblocks
The `preg_replace()` call to remove the existing docblock returns null if the model has a large, existing docblock (more than approximately 50 lines on my machine).
`preg_last_error()` returns 6 (`PREG_JIT_STACKLIMIT_ERROR `).

Having large existing docblocks is not that uncommon when using `barryvdh/laravel-ide-helper` to write docblock annotations for properties and methods.

I managed to fix the issue by simplifying the regex to `#(\n?\/\*\*.*)[\n]?%s#ms`, but I don't know if this works in all possible use cases.

Setting `pcre.jit=0` in php.ini also fixes the issue.

Tested on Windows with PHP 7.3 and 7.1

### PR DESCRIPTION
**Pull request by atymic**
- [x] Added or updated tests
- [x] Added or updated the [README.md](../README.md)
- [x] Detailed changes in the [CHANGELOG.md](../CHANGELOG.md) unreleased section

**Related Issue/Intent**

Closes #120 

**Changes**

Added a failing test case, fixed with suggested regex from the issue.

**Breaking changes**

N/A

### CODE REVIEW

**Comment by atymic** [comment]
Actually, the regex suggested seems to be broken (we end up stripping newlines from the docblock).

Will try and come up with a better one.

**Comment by atymic** [comment]
Tests should not be passing 🙃 
Will fix, please hold off on merging.

**Comment by BenSampo** [comment]
Should I close this one @atymic ?

**Comment by atymic** [comment]
I should still probably fix this 🙈 I'll try and take another look next week.

**Comment by atymic** [comment]
See #157

**Pull request closed without merging**
