### PR TITLE
Added PHP 8 support

### LINKED ISSUE #196: PHP 8
Any blocker for updating the composer json to also support php8?

### PR DESCRIPTION
**Pull request by kurucu**
- [x] Added PHP 8 to composer.json
- [x] Added PHP 8 to travis test matrix

**Related Issue/Intent**

Resolves #196 

**Changes**

As detailed above.

**Breaking changes**

None. All tests pass.

### CODE REVIEW

**Comment by kurucu** [comment]
It seems that Travis isn't ready for PHP8 yet.

**Comment by atymic** [comment]
Travis now costs money, time to move to GH actions?
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by BenSampo** [comment]
If someone would like to PR github actions I'd be happy to move away from Travis. I don't have time to look at it myself right now.

**Comment by kurucu** [comment]
Seems to be superseded by a passing #199

**Pull request closed without merging**
