### PR TITLE
Formatting, comments and codestyle

### PR DESCRIPTION
**Pull request by spawnia**
Only a few nonfunctional reformattings and added comments.

I added `composer check-style` to run in Travis. It seems as though the GitHub connection to Travis is gone though, i can not see the tests running in this PR. @BenSampo can you reenable it?

### CODE REVIEW

**Comment by BenSampo** [comment]
Travis integration should be working again now.

**Comment by BenSampo** [comment]
@spawnia Please can you check broken tests and fix merge conflict.

**Comment by spawnia** [comment]
Looks like it is failing because of a bug in `php_codesniffer` https://travis-ci.org/BenSampo/laravel-enum/jobs/570702341

I plan to improve the test setup through https://github.com/BenSampo/laravel-enum/pull/84 first, then this should pass.

**Comment by spawnia** [comment]
Removed `composer check-style` for now to make the pipeline pass. We can work on that in #84, this one should be good to go.

**Pull request merged**
