### PR TITLE
Add pipe validation

### PR DESCRIPTION
**Pull request by uguurozkan**
I've added some aliases for the rules in order to use them in pipe validations like 
```php
'user_type' => 'bail|required|enum_value:' . UserType::class,
```

I'd like to write test cases but I don't know how to create a test for this type of validation. However, I tested it in one of my projects and it worked.

### CODE REVIEW

**Comment by wi1dcard** [comment]
Nice job

**Comment by BenSampo** [comment]
Hey @uguurozkan, thanks for your work on this. I've added some tests and made a few changes to your PR. Will merge and tag shortly.

Thanks! 👍

**Comment by uguurozkan** [comment]
@BenSampo I think you tagged wrong commit. Because
https://github.com/BenSampo/laravel-enum/releases/tag/1.13.0 and 
https://github.com/BenSampo/laravel-enum/releases/tag/1.12.0 have the same hash.

**Comment by BenSampo** [comment]
Doh! Yes I did. Should be sorted now.

**Pull request merged**
