### PR TITLE
Enable automatic package discovery from testbench

### PR DESCRIPTION
**Pull request by crynobone**
**Changes**

Demonstrate adding "package discovery" when running Larastan. nunomaduro/larastan#1384

**Breaking changes**

None

### CODE REVIEW

**Comment by szepeviktor** [comment]
Larastan should find service providers.

**Comment by spawnia** [comment]
Are you sure the config file and the extra step are required? `vendor/bin/testbench` seems to pick up the service provider on its own:

image

**Comment by crynobone** [comment]
> Are you sure the config file and the extra step are required?

Calling `vendor/bin/testbench` adds a symlink between `vendor/orchestra/testbench-core/laravel/vendor` to your package's `vendor`. Calling `vendor/bin/testbench package:discover` ensure `vendor/orchestra/testbench-core/laravel/bootstrap/packages.php` contains the full packages available within `vendor`.

**Comment by crynobone** [comment]
image

Remove `testbench.yaml` and just use `vendor/bin/testbench package:discover`

**Comment by spawnia** [comment]
What do you think about including the call in `composer.json` section `scripts.post-autoload-dump`, just like a Laravel app does? That way, it works in local development automatically.

**Comment by crynobone** [comment]
That would be also another way of doing it, also suggested in the documentation: https://packages.tools/testbench/getting-started/introduction.html#installation

**Comment by spawnia** [comment]
Thanks @crynobone - looks like I have a couple of Laravel projects to update. Thank you very much for your work on Testbench.

**Pull request merged**
