### PR TITLE
Upgrade phpstan to v0.12.9

### LINKED ISSUE #122: PHPStan v0.12 error
Using laravel-enum v1.30 PHPStan v0.12.8 analyse fails with:

```
PHP Fatal error:  Class BenSampo\Enum\PHPStan\EnumMethodReflection contains 7 abstract methods and must therefore be declared abstract or implement the remaining methods (PHPStan\Reflection\MethodReflection::isDeprecated, PHPStan\Reflection\MethodReflection::getDeprecatedDescription, PHPStan\Reflection\MethodReflection::isFinal, ...) in /home/rjacinto/src/genesis-web/vendor/bensampo/laravel-enum/src/PHPStan/EnumMethodReflection.php on line 11
```

I've created  PR #121 to fix this issue.

### PR DESCRIPTION
**Pull request by Xint0-elab**
- [x] Added or updated tests
- [ ] Added or updated the [README.md](README.md)
- [x] Detailed changes in the [CHANGELOG.md](CHANGELOG.md) unreleased section

**Related Issue/Intent**

Fixes #122 (Support v0.12 of PHPStan)

**Changes**

Now `EnumMethodReflection` implements the following methods:
- `getDeprecatedDescription` - Will return the `@deprecated` tag description of the generating constant.
- `getDocComment` - Will return null.
- `getThrowType` - Will return null.
- `hasSideEffects` - Will return `TrinaryLogic::No`.
- `isDeprecated` - Will return the `isDeprecated` value of the generating constant.
- `isFinal` - Will return `TrinaryLogic::No`.
- `isInternal` - Will return the `isInternal` value of the generating constant.

**Breaking changes**

Should not break any functionality.

### CODE REVIEW

**Comment by BenSampo** [comment]
@spawnia I don't use PHPStan. Would you give me some feedback on this PR? Does #119 supersede this?

**Comment by spawnia** [comment]
This does basically the same thing as #119. However, i like the additional tests and some cases that i did not have in mind were considered.

@Xint0-elab can you rebase your PR on top of the latest changes in `master` so we can converge on the optimal solution?

**Comment by Xint0-elab** [comment]
@spawnia Sure thing

**Comment by BenSampo** [comment]
Thanks @Xint0-elab 👍

**Comment by spawnia** [comment]
Awesome, one more step in making the PHP world a (type-)safer place :)

**Pull request merged**
